[COOKIES]
_fwb = 150r4Q5wK0yq1b5RDTDn7cq.1753524124532
PCID = 17535241246108694755228
TKT_POC_ID = WP19
MAC_T = "fH2/f7duFWy4ZLwt+GBVbwGk7RbVl3GmaqBdSrl7NU/t0VsatlqN+x/MWw+DGaFoBSwrOj8b2dJzz8WFpVIEow=="
keyCookie_T = 1007828360
i18next = EN
JSESSIONID = 9AF35D7F592FABF83D0B33E217F42913
NetFunnel_ID = WP15
wcs_bt = s_322bdbd6fd48:1772960747

[HEADERS]
User-Agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36
Referer = https://tkglobal.melon.com/reservation/popup/onestop.htm
Accept = text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01
Accept-Language = zh-CN,zh;q=0.9
Connection = keep-alive
Content-Type = application/x-www-form-urlencoded; charset=UTF-8

[PROXIES]
proxy1 = http://a2bs5:a2bs5@175.202.26.87:23361
proxy2 = http://a2bs5:a2bs5@59.2.74.239:23361
proxy3 = http://a2bs5:a2bs5@175.201.7.146:23361
proxy4 = http://a2bs5:a2bs5@175.201.7.248:23361
proxy5 = http://a2bs5:a2bs5@59.0.117.85:23361

[settings]
timedelay= 500
username=weichun+gong
memberkey = 1007828360
telNum= 15864230665
eventid = 212638

scheduleno = 100001
#0-先选区域再选座位；1-直接选座位
seattype = 0
#区域编号
areaNo = E3
#座位ID
seatid = ""